
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = match:class ^(yazi-float)$, float on, center on, size monitor_w*0.7 monitor_h*0.7

layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center

layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

layerrule = blur on, match:namespace ^rofi$
layerrule = ignore_alpha 0.3, match:namespace ^rofi$
xwayland {
    force_zero_scaling = true
}

windowrule = float on, match:title (Open File)
windowrule = float on, match:title (Open Folder)
windowrule = float on, match:class (blueman-manager)
windowrule = float on, match:class (org.pulseaudio.pavucontrol), size monitor_w*0.5 monitor_h*0.5
windowrule = stay_focused on, match:tag focusing
